### ISSUE TITLE
Colon in lists processing wrong

### ISSUE THREAD

**Issue by kvaps** [andreazorzetto/yh#15]
example yaml:
```yaml
urls:
  - https://github.com/kvaps
  - "https://github.com/kvaps"
```
output:
<img src="https://user-images.githubusercontent.com/7556217/92031874-95df2680-ed69-11ea-8838-9c90323a669e.gif" width="400"  />

**Comment by kvaps** [comment]
Another yaml:

```yaml
metadata:
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
```

![7](https://user-images.githubusercontent.com/7556217/92392931-558ff780-f11f-11ea-8cb8-c1e41ff8980c.gif)

**Comment by andreazorzetto** [comment]
Fixing this now in dev

**Comment by andreazorzetto** [comment]
Fixed in the latest release

**Comment by andreazorzetto** [comment]
Working on the second comment.
Right now it's recognized as non valid yaml (colon without space) I need to look into this better

**Comment by andreazorzetto** [comment]
All fixed in version 0.3.2
Hopefully this works for you 
Please let me know in case

**Comment by kvaps** [comment]
You''re awesome, thank you!

**Comment by kvaps** [comment]
just found another problematic yaml:

```
  containerStatuses:
  - containerID: docker://44c407cf710579e4001f7c75eebb2000895231d9ba307f059cca57ae01c1ed35
    image: kvaps/kubernetes-tools:v1.19.1
    imageID: docker-pullable://kvaps/kubernetes-tools@sha256:412398e6026f9a47ac904c52d79ee806bd515929c7fbd3d7b28e05b8e24724e7
    lastState: {}
    name: kubeadm
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://44c407cf710579e4001f7c75eebb2000895231d9ba307f059cca57ae01c1ed35
        exitCode: 0
        finishedAt: "2020-10-17T12:00:03Z"
        reason: Completed
        startedAt: "2020-10-17T12:00:03Z"
```

yh now removes colons from some values

```diff
-  containerStatuses:
+  containerStatuses: 
   - containerID: docker://44c407cf710579e4001f7c75eebb2000895231d9ba307f059cca57ae01c1ed35
-    image: kvaps/kubernetes-tools:v1.19.1
+    image: kvaps/kubernetes-toolsv1.19.1
     imageID: docker-pullable://kvaps/kubernetes-tools@sha256:412398e6026f9a47ac904c52d79ee806bd515929c7fbd3d7b28e05b8e24724e7
     lastState: {}
     name: kubeadm
     ready: false
     restartCount: 0
     started: false
-    state:
-      terminated:
+    state: 
+      terminated: 
         containerID: docker://44c407cf710579e4001f7c75eebb2000895231d9ba307f059cca57ae01c1ed35
         exitCode: 0
-        finishedAt: "2020-10-17T12:00:03Z"
+        finishedAt: "2020-10-17T120003Z"
         reason: Completed
-        startedAt: "2020-10-17T12:00:03Z"
+        startedAt: "2020-10-17T120003Z"
```
