### ISSUE TITLE
Can I highlight kustomize output (yaml)

### ISSUE THREAD

**Issue by exocode** [andreazorzetto/yh#22]
Somehow I cant get the output of `kustomize` get highlighted:

`kustomize build k8s/kustomize/overlays/dev | yh`

output: `zsh: command not found:  yh`

but using with kubectl works: `kubectl get all -o yaml | yh`

output is colorized: 
```yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
```

_I am using BigSur MacOS_
