### ISSUE TITLE
Swallows comment-only lines

### ISSUE THREAD

**Issue by ahmetb** [andreazorzetto/yh#24]
Input:
```yaml
spec:
  # comment1
  progressDeadlineSeconds: 600
  # comment2
  replicas: 3
  # comment3
  revisionHistoryLimit: 10
```
Output:
<img width="625" alt="image" src="https://github.com/andreazorzetto/yh/assets/159209/73208f0d-7d72-43de-8119-ce6e3deebc91">
